<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitef637136d5fae12e96d0c7e8c829c969
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Platonic\\Framework\\' => 19,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Platonic\\Framework\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Platonic\\Framework\\Customizer\\Customizer' => __DIR__ . '/../..' . '/includes/Customizer/Customizer.php',
        'Platonic\\Framework\\Customizer\\Interface\\Customizer_Rules' => __DIR__ . '/../..' . '/includes/Customizer/Interface/Customizer_Rules.php',
        'Platonic\\Framework\\Settings\\Example\\Plugin_Settings_Page_Example' => __DIR__ . '/../..' . '/includes/Settings/Example/Plugin_Settings_Page_Example.php',
        'Platonic\\Framework\\Settings\\Example\\Settings_Page_Example' => __DIR__ . '/../..' . '/includes/Settings/Example/Settings_Page_Example.php',
        'Platonic\\Framework\\Settings\\Example\\Theme_Settings_Page' => __DIR__ . '/../..' . '/includes/Settings/Example/Theme_Settings_Page.php',
        'Platonic\\Framework\\Settings\\Interface\\Plugin_Settings_Page_Rules' => __DIR__ . '/../..' . '/includes/Settings/Interface/Plugin_Settings_Page_Rules.php',
        'Platonic\\Framework\\Settings\\Interface\\Settings_Page_Rules' => __DIR__ . '/../..' . '/includes/Settings/Interface/Settings_Page_Rules.php',
        'Platonic\\Framework\\Settings\\Interface\\Settings_Rules' => __DIR__ . '/../..' . '/includes/Settings/Interface/Settings_Rules.php',
        'Platonic\\Framework\\Settings\\Interface\\Theme_Settings_Page_Rules' => __DIR__ . '/../..' . '/includes/Settings/Interface/Theme_Settings_Page_Rules.php',
        'Platonic\\Framework\\Settings\\Plugin_Settings' => __DIR__ . '/../..' . '/includes/Settings/Plugin_Settings.php',
        'Platonic\\Framework\\Settings\\Settings' => __DIR__ . '/../..' . '/includes/Settings/Settings.php',
        'Platonic\\Framework\\Settings\\Settings_Page' => __DIR__ . '/../..' . '/includes/Settings/Settings_Page.php',
        'Platonic\\Framework\\Settings\\Theme_Settings' => __DIR__ . '/../..' . '/includes/Settings/Theme_Settings.php',
        'Platonic\\Framework\\Settings\\Trait\\Menu_Page_Handler' => __DIR__ . '/../..' . '/includes/Settings/Trait/Menu_Page_Handler.php',
        'Platonic\\Framework\\Settings\\Trait\\Option_Lifecycle_Manager' => __DIR__ . '/../..' . '/includes/Settings/Trait/Option_Lifecycle_Manager.php',
        'Platonic\\Framework\\Settings\\Trait\\Sanitization' => __DIR__ . '/../..' . '/includes/Settings/Trait/Sanitization.php',
        'Platonic\\Framework\\Settings\\Trait\\Settings_Fields' => __DIR__ . '/../..' . '/includes/Settings/Trait/Settings_Fields.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitef637136d5fae12e96d0c7e8c829c969::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitef637136d5fae12e96d0c7e8c829c969::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitef637136d5fae12e96d0c7e8c829c969::$classMap;

        }, null, ClassLoader::class);
    }
}
