<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Platonic\\Framework\\Customizer\\Customizer' => $baseDir . '/includes/Customizer/Customizer.php',
    'Platonic\\Framework\\Customizer\\Interface\\CustomizerRules' => $baseDir . '/includes/Customizer/Interface/CustomizerRules.php',
    'Platonic\\Framework\\Settings\\Example\\PluginSettingsPageExample' => $baseDir . '/includes/Settings/Example/PluginSettingsPageExample.php',
    'Platonic\\Framework\\Settings\\Example\\SettingsPageExample' => $baseDir . '/includes/Settings/Example/SettingsPageExample.php',
    'Platonic\\Framework\\Settings\\Example\\ThemeSettingsPage' => $baseDir . '/includes/Settings/Example/ThemeSettingsPage.php',
    'Platonic\\Framework\\Settings\\Interface\\PluginSettingsPageRules' => $baseDir . '/includes/Settings/Interface/PluginSettingsPageRules.php',
    'Platonic\\Framework\\Settings\\Interface\\SettingsPageRules' => $baseDir . '/includes/Settings/Interface/SettingsPageRules.php',
    'Platonic\\Framework\\Settings\\Interface\\SettingsRules' => $baseDir . '/includes/Settings/Interface/SettingsRules.php',
    'Platonic\\Framework\\Settings\\Interface\\ThemeSettingsPageRules' => $baseDir . '/includes/Settings/Interface/ThemeSettingsPageRules.php',
    'Platonic\\Framework\\Settings\\PluginSettings' => $baseDir . '/includes/Settings/PluginSettings.php',
    'Platonic\\Framework\\Settings\\Settings' => $baseDir . '/includes/Settings/Settings.php',
    'Platonic\\Framework\\Settings\\ThemeSettings' => $baseDir . '/includes/Settings/ThemeSettings.php',
    'Platonic\\Framework\\Settings\\Trait\\OptionsPage' => $baseDir . '/includes/Settings/Trait/OptionsPage.php',
    'Platonic\\Framework\\Settings\\Trait\\Sanitization' => $baseDir . '/includes/Settings/Trait/Sanitization.php',
    'Platonic\\Framework\\Settings\\Trait\\SettingsFields' => $baseDir . '/includes/Settings/Trait/SettingsFields.php',
);
