<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitef637136d5fae12e96d0c7e8c829c969
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInitef637136d5fae12e96d0c7e8c829c969', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitef637136d5fae12e96d0c7e8c829c969', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInitef637136d5fae12e96d0c7e8c829c969::getInitializer($loader));

        $loader->register(true);

        return $loader;
    }
}
